# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import listing_pb2 as listing__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in listing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ListingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateListing = channel.unary_unary(
                '/listing.ListingService/CreateListing',
                request_serializer=listing__pb2.CreateListingRequest.SerializeToString,
                response_deserializer=listing__pb2.CreateListingResponse.FromString,
                _registered_method=True)
        self.GetListing = channel.unary_unary(
                '/listing.ListingService/GetListing',
                request_serializer=listing__pb2.GetListingRequest.SerializeToString,
                response_deserializer=listing__pb2.GetListingResponse.FromString,
                _registered_method=True)
        self.ApproveListing = channel.unary_unary(
                '/listing.ListingService/ApproveListing',
                request_serializer=listing__pb2.ApproveListingRequest.SerializeToString,
                response_deserializer=listing__pb2.ApproveListingResponse.FromString,
                _registered_method=True)
        self.RejectListing = channel.unary_unary(
                '/listing.ListingService/RejectListing',
                request_serializer=listing__pb2.RejectListingRequest.SerializeToString,
                response_deserializer=listing__pb2.RejectListingResponse.FromString,
                _registered_method=True)
        self.ListListings = channel.unary_unary(
                '/listing.ListingService/ListListings',
                request_serializer=listing__pb2.ListListingsRequest.SerializeToString,
                response_deserializer=listing__pb2.ListListingsResponse.FromString,
                _registered_method=True)
        self.StreamNewListings = channel.unary_stream(
                '/listing.ListingService/StreamNewListings',
                request_serializer=listing__pb2.Empty.SerializeToString,
                response_deserializer=listing__pb2.Listing.FromString,
                _registered_method=True)


class ListingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListListings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNewListings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateListing': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateListing,
                    request_deserializer=listing__pb2.CreateListingRequest.FromString,
                    response_serializer=listing__pb2.CreateListingResponse.SerializeToString,
            ),
            'GetListing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListing,
                    request_deserializer=listing__pb2.GetListingRequest.FromString,
                    response_serializer=listing__pb2.GetListingResponse.SerializeToString,
            ),
            'ApproveListing': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveListing,
                    request_deserializer=listing__pb2.ApproveListingRequest.FromString,
                    response_serializer=listing__pb2.ApproveListingResponse.SerializeToString,
            ),
            'RejectListing': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectListing,
                    request_deserializer=listing__pb2.RejectListingRequest.FromString,
                    response_serializer=listing__pb2.RejectListingResponse.SerializeToString,
            ),
            'ListListings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListListings,
                    request_deserializer=listing__pb2.ListListingsRequest.FromString,
                    response_serializer=listing__pb2.ListListingsResponse.SerializeToString,
            ),
            'StreamNewListings': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNewListings,
                    request_deserializer=listing__pb2.Empty.FromString,
                    response_serializer=listing__pb2.Listing.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'listing.ListingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('listing.ListingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listing.ListingService/CreateListing',
            listing__pb2.CreateListingRequest.SerializeToString,
            listing__pb2.CreateListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listing.ListingService/GetListing',
            listing__pb2.GetListingRequest.SerializeToString,
            listing__pb2.GetListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listing.ListingService/ApproveListing',
            listing__pb2.ApproveListingRequest.SerializeToString,
            listing__pb2.ApproveListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listing.ListingService/RejectListing',
            listing__pb2.RejectListingRequest.SerializeToString,
            listing__pb2.RejectListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListListings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listing.ListingService/ListListings',
            listing__pb2.ListListingsRequest.SerializeToString,
            listing__pb2.ListListingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNewListings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/listing.ListingService/StreamNewListings',
            listing__pb2.Empty.SerializeToString,
            listing__pb2.Listing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
