# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: category.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'category.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61tegory.proto\x12\x08\x63\x61tegory\"8\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"%\n\x15\x43reateCategoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\">\n\x16\x43reateCategoryResponse\x12$\n\x08\x63\x61tegory\x18\x01 \x01(\x0b\x32\x12.category.Category\" \n\x12GetCategoryRequest\x12\n\n\x02id\x18\x01 \x01(\t\";\n\x13GetCategoryResponse\x12$\n\x08\x63\x61tegory\x18\x01 \x01(\x0b\x32\x12.category.Category\"6\n\x15ListCategoriesRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"U\n\x16ListCategoriesResponse\x12&\n\ncategories\x18\x01 \x03(\x0b\x32\x12.category.Category\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x32\x87\x02\n\x0f\x43\x61tegoryService\x12S\n\x0e\x43reateCategory\x12\x1f.category.CreateCategoryRequest\x1a .category.CreateCategoryResponse\x12J\n\x0bGetCategory\x12\x1c.category.GetCategoryRequest\x1a\x1d.category.GetCategoryResponse\x12S\n\x0eListCategories\x12\x1f.category.ListCategoriesRequest\x1a .category.ListCategoriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'category_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORY']._serialized_start=28
  _globals['_CATEGORY']._serialized_end=84
  _globals['_CREATECATEGORYREQUEST']._serialized_start=86
  _globals['_CREATECATEGORYREQUEST']._serialized_end=123
  _globals['_CREATECATEGORYRESPONSE']._serialized_start=125
  _globals['_CREATECATEGORYRESPONSE']._serialized_end=187
  _globals['_GETCATEGORYREQUEST']._serialized_start=189
  _globals['_GETCATEGORYREQUEST']._serialized_end=221
  _globals['_GETCATEGORYRESPONSE']._serialized_start=223
  _globals['_GETCATEGORYRESPONSE']._serialized_end=282
  _globals['_LISTCATEGORIESREQUEST']._serialized_start=284
  _globals['_LISTCATEGORIESREQUEST']._serialized_end=338
  _globals['_LISTCATEGORIESRESPONSE']._serialized_start=340
  _globals['_LISTCATEGORIESRESPONSE']._serialized_end=425
  _globals['_CATEGORYSERVICE']._serialized_start=428
  _globals['_CATEGORYSERVICE']._serialized_end=691
# @@protoc_insertion_point(module_scope)
