worker_processes 1;

events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/listings {
            proxy_pass http://listing_service:8000;
        }
    }
}
